name: Style

on: [push, pull_request]

jobs:
  black-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        version: "22.3.0"
  
  flake8-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install flake8==4.0.1
    - run: flake8 .
  
  tekton-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g tekton-lint
    - run: tekton-lint tekton/*.yaml

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install yamllint==1.26.3
    - run: "yamllint -d '{rules: {indentation: {indent-sequences: consistent}}}' ."
